// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prism.ApiService.Data;

#nullable disable

namespace Prism.ApiService.Migrations
{
    [DbContext(typeof(PrismDBContext))]
    [Migration("20260809055747_SeedResearchPaperDomain")]
    partial class SeedResearchPaperDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prism.ApiService.Data.FileRecord", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("FileId")
                        .HasName("pk_file_records");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("ix_file_records_chat_id");

                    b.ToTable("file_records", (string)null);
                });

            modelBuilder.Entity("Prism.ApiService.Data.PrismDocument", b =>
                {
                    b.Property<Guid>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("chat_id");

                    b.Property<string>("ChatTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chat_title");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("ChatId")
                        .HasName("pk_prism_documents");

                    b.ToTable("prism_documents", (string)null);
                });

            modelBuilder.Entity("Prism.ApiService.Data.Schemas.DocumentExtractor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<string>("Fields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("fields");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<Guid?>("LatestRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_run_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_document_extractors");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("ix_document_extractors_domain_id");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_document_extractors_file_id");

                    b.ToTable("document_extractors", (string)null);
                });

            modelBuilder.Entity("Prism.ApiService.Data.Schemas.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PromptSchema")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("prompt_schema");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_domains");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_domains_name");

                    b.ToTable("domains", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "research-paper",
                            PromptSchema = "{}",
                            UpdatedAt = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Prism.ApiService.Data.Schemas.PaperClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClaimSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_summary");

                    b.Property<string>("ClaimTextVerbatim")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_text_verbatim");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentExtractorId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_extractor_id");

                    b.Property<Guid>("ExtractionRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("extraction_run_id");

                    b.Property<string>("GroundingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grounding_status");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<bool>("Missing")
                        .HasColumnType("boolean")
                        .HasColumnName("missing");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_paper_claims");

                    b.HasIndex("ExtractionRunId")
                        .HasDatabaseName("ix_paper_claims_extraction_run_id");

                    b.HasIndex("DocumentExtractorId", "Label")
                        .HasDatabaseName("ix_paper_claims_document_extractor_id_label");

                    b.ToTable("paper_claims", (string)null);
                });

            modelBuilder.Entity("Prism.ApiService.Data.FileRecord", b =>
                {
                    b.HasOne("Prism.ApiService.Data.PrismDocument", null)
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_records_prism_documents_chat_id");
                });

            modelBuilder.Entity("Prism.ApiService.Data.Schemas.DocumentExtractor", b =>
                {
                    b.HasOne("Prism.ApiService.Data.Schemas.Domain", "Domain")
                        .WithMany("DocumentExtractors")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_extractors_domains_domain_id");

                    b.HasOne("Prism.ApiService.Data.FileRecord", "FileRecord")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_extractors_file_records_file_id");

                    b.Navigation("Domain");

                    b.Navigation("FileRecord");
                });

            modelBuilder.Entity("Prism.ApiService.Data.Schemas.PaperClaim", b =>
                {
                    b.HasOne("Prism.ApiService.Data.Schemas.DocumentExtractor", "DocumentExtractor")
                        .WithMany("PaperClaims")
                        .HasForeignKey("DocumentExtractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paper_claims_document_extractors_document_extractor_id");

                    b.OwnsMany("Prism.ApiService.Data.Schemas.EvidenceSpan", "EvidenceSpans", b1 =>
                        {
                            b1.Property<Guid>("PaperClaimId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("GroundingStatus")
                                .IsRequired();

                            b1.Property<int?>("PageNumber");

                            b1.Property<string>("SectionHeader");

                            b1.Property<string>("SourceSection")
                                .IsRequired();

                            b1.Property<string>("SourceText")
                                .IsRequired();

                            b1.HasKey("PaperClaimId", "__synthesizedOrdinal");

                            b1.ToTable("paper_claims");

                            b1
                                .ToJson("evidence_spans")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PaperClaimId")
                                .HasConstraintName("fk_paper_claims_paper_claims_paper_claim_id");
                        });

                    b.Navigation("DocumentExtractor");

                    b.Navigation("EvidenceSpans");
                });

            modelBuilder.Entity("Prism.ApiService.Data.Schemas.DocumentExtractor", b =>
                {
                    b.Navigation("PaperClaims");
                });

            modelBuilder.Entity("Prism.ApiService.Data.Schemas.Domain", b =>
                {
                    b.Navigation("DocumentExtractors");
                });
#pragma warning restore 612, 618
        }
    }
}
