import { Link } from "react-router-dom";

export function Terms() {
  return (
    <div className="min-h-dvh w-full font-sans bg-[#F9F9F8] bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:16px_16px] px-6 py-12 md:py-20 text-ink">
      <div className="w-full max-w-[680px] mx-auto">
        <Link to="/login" className="text-sm text-ink-muted hover:text-ink transition-colors mb-12 inline-block">
          &larr; Back to login
        </Link>
        <h1 className="font-['Georgia','Times_New_Roman',serif] text-3xl md:text-4xl font-medium mb-6">Terms of Use</h1>
        <p className="text-sm text-ink-muted mb-8">Last updated: September 2026</p>
        
        <div className="text-ink text-base leading-relaxed space-y-6">
          <p>
            PRISM is an independent, actively-developed engineering project. It is provided as a demonstration of a research-paper claim-auditing system, not as a commercial or production service.
          </p>

          <h2 className="font-['Georgia','Times_New_Roman',serif] text-xl font-medium mt-10 mb-4">No warranty</h2>
          <p>
            PRISM is provided "as is," without warranty of any kind, express or implied. The audit results, verdicts, and claim assessments PRISM produces are generated by AI models and may be incomplete or incorrect. Nothing in PRISM's output should be treated as a substitute for your own review of a paper.
          </p>

          <h2 className="font-['Georgia','Times_New_Roman',serif] text-xl font-medium mt-10 mb-4">No uptime or support commitment</h2>
          <p>
            As a demo project, PRISM has no guaranteed availability, backup policy, or support SLA. Features, data, and the service itself may change or become unavailable without notice.
          </p>

          <h2 className="font-['Georgia','Times_New_Roman',serif] text-xl font-medium mt-10 mb-4">What not to upload</h2>
          <p>
            Do not upload papers or documents that are confidential, that you do not have the right to share, or that contain personal or sensitive information you would not want processed by third-party AI providers. See the Privacy Policy for how uploaded content is processed.
          </p>

          <h2 className="font-['Georgia','Times_New_Roman',serif] text-xl font-medium mt-10 mb-4">Ownership</h2>
          <p>
            You retain ownership of any paper or content you upload. Uploading a paper to PRISM does not transfer any rights in that content.
          </p>

          <h2 className="font-['Georgia','Times_New_Roman',serif] text-xl font-medium mt-10 mb-4">Changes</h2>
          <p>
            These terms may be updated as the project develops. Continued use of PRISM after a change constitutes acceptance of the updated terms.
          </p>

          <h2 className="font-['Georgia','Times_New_Roman',serif] text-xl font-medium mt-10 mb-4">Contact</h2>
          <p>
            nitin8764@live.com
          </p>
        </div>
      </div>
    </div>
  );
}
